# Generated by Django 6.0.1 on 2026-09-07 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
        ("stores", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="assigned_stores",
            field=models.ManyToManyField(
                blank=True,
                help_text="Stores accessible by this user if role is Store Manager",
                related_name="assigned_managers",
                to="stores.store",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="device_id",
            field=models.CharField(
                blank=True,
                help_text="Legacy device ID if applicable",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("super_admin", "Super Admin"),
                    ("admin", "Admin"),
                    ("content_manager", "Content Manager"),
                    ("store_manager", "Store Manager"),
                    ("monitoring_manager", "Monitoring Manager"),
                    ("staff", "Staff"),
                    ("kiosk", "Kiosk (Legacy)"),
                ],
                default="admin",
                help_text="CMS user role",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True,
                help_text="Unique login ID. Auto-generated if left blank.",
                max_length=150,
                unique=True,
            ),
        ),
    ]
