# Generated by Django 6.0.1 on 2026-09-07 05:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("kiosks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("KIOSK_OFFLINE", "Kiosk Offline"),
                            ("LOW_BATTERY", "Low Battery"),
                            ("SYNC_FAILED", "Sync Failed"),
                            ("APP_ERROR", "App Error"),
                            ("OLD_APP_VERSION", "Old App Version"),
                            ("CONTENT_OUTDATED", "Content Outdated"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="WARNING",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("opened_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "resolved_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "kiosk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="kiosks.kioskdevice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alert",
                "verbose_name_plural": "Alerts",
                "ordering": ["-opened_at"],
                "indexes": [
                    models.Index(
                        fields=["kiosk", "resolved_at"],
                        name="monitoring__kiosk_i_a23b7f_idx",
                    ),
                    models.Index(
                        fields=["alert_type"], name="monitoring__alert_t_b20e11_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="KioskEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("BOOT", "Boot"),
                            ("HEARTBEAT", "Heartbeat"),
                            ("APP_STARTED", "App Started"),
                            ("APP_STOPPED", "App Stopped"),
                            ("APP_CRASH", "App Crash"),
                            ("SYNC_STARTED", "Sync Started"),
                            ("SYNC_COMPLETED", "Sync Completed"),
                            ("SYNC_FAILED", "Sync Failed"),
                            ("NETWORK_CONNECTED", "Network Connected"),
                            ("NETWORK_DISCONNECTED", "Network Disconnected"),
                            ("LOW_BATTERY", "Low Battery"),
                            ("SCREEN_OFF", "Screen Off"),
                            ("SCREEN_ON", "Screen On"),
                            ("ERROR", "Error"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="INFO",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "kiosk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="kiosks.kioskdevice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kiosk Event",
                "verbose_name_plural": "Kiosk Events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["kiosk", "-created_at"],
                        name="monitoring__kiosk_i_4d5d40_idx",
                    ),
                    models.Index(
                        fields=["event_type"], name="monitoring__event_t_9f7e06_idx"
                    ),
                ],
            },
        ),
    ]
