# Generated by Django 5.2.17 on 2026-09-22 06:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kiosks", "0005_kioskdevice_assigned_products"),
        ("monitoring", "0001_initial"),
        ("products", "0002_add_category_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="KioskUsageSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "session_id",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("started_at", models.DateTimeField(db_index=True)),
                (
                    "ended_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("duration_seconds", models.PositiveIntegerField(default=0)),
                ("total_clicks", models.PositiveIntegerField(default=0)),
                ("products_viewed_count", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "kiosk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_sessions",
                        to="kiosks.kioskdevice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kiosk Usage Session",
                "verbose_name_plural": "Kiosk Usage Sessions",
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["kiosk", "-started_at"],
                        name="monitoring__kiosk_i_3ae509_idx",
                    ),
                    models.Index(
                        fields=["started_at"], name="monitoring__started_c8a738_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProductInteraction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("CLICK", "Product Card Click"),
                            ("VIEW_DETAIL", "Full Detail View"),
                            ("SPEC_TAB_CLICK", "Specification Tab Click"),
                            ("BROCHURE_VIEW", "Brochure View"),
                            ("WHITEBOARD_OPEN", "Whiteboard Launch"),
                            ("SEARCH_SELECT", "Search Selection"),
                            ("CATEGORY_CLICK", "Category Click"),
                        ],
                        db_index=True,
                        default="CLICK",
                        max_length=50,
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True
                    ),
                ),
                ("duration_seconds", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "kiosk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_interactions",
                        to="kiosks.kioskdevice",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interactions",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Interaction",
                "verbose_name_plural": "Product Interactions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["kiosk", "-created_at"],
                        name="monitoring__kiosk_i_5e6267_idx",
                    ),
                    models.Index(
                        fields=["product", "-created_at"],
                        name="monitoring__product_3b495c_idx",
                    ),
                    models.Index(
                        fields=["interaction_type"],
                        name="monitoring__interac_680a39_idx",
                    ),
                    models.Index(
                        fields=["session_id"], name="monitoring__session_dee65b_idx"
                    ),
                ],
            },
        ),
    ]
