# Generated by Django 6.0.1 on 2026-09-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0002_kioskusagesession_productinteraction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kioskevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("BOOT", "Boot"),
                    ("HEARTBEAT", "Heartbeat"),
                    ("APP_STARTED", "App Started"),
                    ("APP_STOPPED", "App Stopped"),
                    ("APP_CRASH", "App Crash"),
                    ("SYNC_STARTED", "Sync Started"),
                    ("SYNC_COMPLETED", "Sync Completed"),
                    ("SYNC_FAILED", "Sync Failed"),
                    ("NETWORK_CONNECTED", "Network Connected"),
                    ("NETWORK_DISCONNECTED", "Network Disconnected"),
                    ("LOW_BATTERY", "Low Battery"),
                    ("SCREEN_OFF", "Screen Off"),
                    ("SCREEN_ON", "Screen On"),
                    ("APP_UPDATE", "App Update"),
                    ("ERROR", "Error"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
    ]
