# Generated by Django 6.0.1 on 2026-09-07 05:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("kiosks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("VIDEO", "Promotional Video"),
                            ("PDF_BROCHURE", "PDF Brochure"),
                            ("TECH_SHEET", "Technical Specification"),
                            ("THREE_D", "3D Asset"),
                        ],
                        default="VIDEO",
                        max_length=50,
                    ),
                ),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="media_assets/"),
                ),
                (
                    "external_url",
                    models.URLField(
                        blank=True,
                        help_text="Alternative external file or embed link",
                        null=True,
                    ),
                ),
                ("file_size_mb", models.FloatField(default=0.0)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kiosk_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="media_assets",
                        to="kiosks.kioskprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
