# Generated by Django 6.1 on 2026-09-08 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediaasset",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media_assets",
                to="products.product",
            ),
        ),
        migrations.AlterField(
            model_name="mediaasset",
            name="asset_type",
            field=models.CharField(
                choices=[
                    ("IMAGE", "Product Image"),
                    ("VIDEO", "Promotional Video"),
                    ("PDF_BROCHURE", "PDF Brochure"),
                    ("TECH_SHEET", "Technical Specification"),
                    ("THREE_D", "3D Asset"),
                ],
                default="VIDEO",
                max_length=50,
            ),
        ),
    ]
