# Generated by Django 6.0.1 on 2026-09-14 05:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_mediaasset_product_alter_mediaasset_asset_type"),
        ("kiosks", "0005_kioskdevice_assigned_products"),
    ]

    operations = [
        migrations.CreateModel(
            name="Screensaver",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Screensaver display title", max_length=255
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="High-resolution screensaver image",
                        upload_to="screensavers/",
                    ),
                ),
                (
                    "orientation",
                    models.CharField(
                        choices=[
                            ("LANDSCAPE", "Landscape (Horizontal - 16:9 / 1920x1080)"),
                            ("PORTRAIT", "Portrait (Vertical - 9:16 / 1080x1920)"),
                            ("BOTH", "Universal (Fits Both)"),
                        ],
                        db_index=True,
                        default="LANDSCAPE",
                        help_text="Monitor orientation mode (Landscape, Portrait, or Universal)",
                        max_length=20,
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Display order sequence in sliding animation",
                    ),
                ),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(
                        default=10, help_text="Slide display duration in seconds"
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True,
                        help_text="Optional caption / overlay text",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Internal notes or description", null=True
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kiosk_profile",
                    models.ForeignKey(
                        blank=True,
                        help_text="Target specific kiosk profile (leave empty for all)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="screensavers",
                        to="kiosks.kioskprofile",
                    ),
                ),
                (
                    "kiosks",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Target specific kiosks (leave empty for all)",
                        related_name="screensavers",
                        to="kiosks.kioskdevice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Screensaver",
                "verbose_name_plural": "Screensavers",
                "ordering": ["display_order", "-created_at"],
            },
        ),
    ]
