from django.urls import path 
from . import views 

urlpatterns = [
    path("", views.admin_dashboard, name="admin_dashboard"),
    path("dashboard/", views.admin_dashboard, name="admin_dashboard_alias"),
    path("kiosks/", views.admin_kiosks, name="admin_kiosks"),
    path("kiosks/add/", views.admin_kiosk_add, name="admin_kiosk_add"),
    path("kiosks/<uuid:kiosk_id>/", views.admin_kiosk_detail, name="admin_kiosk_detail"),
    path("kiosks/<uuid:kiosk_id>/edit/", views.admin_kiosk_edit, name="admin_kiosk_edit"),
    path("products/", views.admin_products, name="admin_products"),
    path("products/add/", views.admin_product_add, name="admin_product_add"),
    path("products/<uuid:product_id>/", views.admin_product_detail, name="admin_product_detail"),
    path("categories/", views.admin_categories, name="admin_categories"),
    path("stores/", views.admin_stores, name="admin_stores"),
    path("stores/<uuid:store_id>/", views.admin_store_detail, name="admin_store_detail"),
    path("users/", views.admin_users, name="admin_users"),
    path("monitoring/", views.admin_monitoring, name="admin_monitoring"),
    path("monitoring/<uuid:kiosk_id>/", views.admin_monitoring_kiosk_detail, name="admin_monitoring_kiosk_detail"),
    path("monitoring/api/live-status/", views.admin_monitoring_live_status, name="admin_monitoring_live_status"),
    path("analytics/", views.admin_analytics, name="admin_analytics"),
    path("analytics/export/", views.admin_analytics_export, name="admin_analytics_export"),
    path("media/", views.admin_media, name="admin_media"),
    path("profile/", views.admin_profile, name="admin_profile"),
    path("settings/", views.admin_settings, name="admin_settings"),
    path("screensavers/", views.admin_screensavers, name="admin_screensavers"),
    path("screensavers/add/", views.admin_screensaver_add, name="admin_screensaver_add"),
    path("screensavers/<uuid:screensaver_id>/", views.admin_screensaver_detail, name="admin_screensaver_detail"),
    path("screensavers/<uuid:screensaver_id>/edit/", views.admin_screensaver_edit, name="admin_screensaver_edit"),
    path("screensavers/<uuid:screensaver_id>/delete/", views.admin_screensaver_delete, name="admin_screensaver_delete"),
    path("screensavers/<uuid:screensaver_id>/toggle/", views.admin_screensaver_toggle_active, name="admin_screensaver_toggle_active"),
    path("releases/", views.admin_releases, name="admin_releases"),
    path("releases/add/", views.admin_release_add, name="admin_release_add"),
    path("releases/<uuid:release_id>/", views.admin_release_detail, name="admin_release_detail"),
]