# Generated by Django 6.0.1 on 2026-09-07 05:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stores", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="KioskProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Profile display name (e.g. Standard, Showroom)",
                        max_length=100,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Profile unique code (e.g. STANDARD, DEMO)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("show_products", models.BooleanField(default=True)),
                ("show_brochures", models.BooleanField(default=True)),
                ("show_technical_documents", models.BooleanField(default=True)),
                ("show_pricing", models.BooleanField(default=True)),
                ("show_videos", models.BooleanField(default=True)),
                ("show_3d_assets", models.BooleanField(default=False)),
                ("show_whiteboard", models.BooleanField(default=False)),
                ("screensaver_enabled", models.BooleanField(default=True)),
                (
                    "screensaver_timeout_seconds",
                    models.PositiveIntegerField(default=300),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Kiosk Profile",
                "verbose_name_plural": "Kiosk Profiles",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="KioskDevice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        db_index=True,
                        help_text="Globally unique physical device ID",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable kiosk name", max_length=255
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ONLINE", "Online"),
                            ("WARNING", "Warning"),
                            ("OFFLINE", "Offline"),
                            ("DISABLED", "Disabled"),
                        ],
                        db_index=True,
                        default="OFFLINE",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "android_version",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("app_version", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "device_model",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "manufacturer",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("screen_width", models.PositiveIntegerField(blank=True, null=True)),
                ("screen_height", models.PositiveIntegerField(blank=True, null=True)),
                ("screen_density", models.FloatField(blank=True, null=True)),
                (
                    "serial_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "last_ip_address",
                    models.GenericIPAddressField(blank=True, null=True),
                ),
                (
                    "network_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("last_heartbeat_at", models.DateTimeField(blank=True, null=True)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                (
                    "current_content_version",
                    models.CharField(default="1", max_length=50),
                ),
                (
                    "desired_content_version",
                    models.CharField(default="1", max_length=50),
                ),
                ("battery_percentage", models.SmallIntegerField(blank=True, null=True)),
                ("screen_on", models.BooleanField(default=True)),
                ("app_running", models.BooleanField(default=True)),
                ("last_error", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "store",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kiosks",
                        to="stores.store",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kiosks",
                        to="kiosks.kioskprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kiosk Device",
                "verbose_name_plural": "Kiosk Devices",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="KioskCredential",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "credential_hash",
                    models.CharField(
                        help_text="PBKDF2/Argon2/Bcrypt hash of device_secret",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "kiosk",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credential",
                        to="kiosks.kioskdevice",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="kioskdevice",
            index=models.Index(
                fields=["device_id"], name="kiosks_kios_device__7b2cd8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="kioskdevice",
            index=models.Index(fields=["store"], name="kiosks_kios_store_i_3dbe00_idx"),
        ),
        migrations.AddIndex(
            model_name="kioskdevice",
            index=models.Index(fields=["status"], name="kiosks_kios_status_0a079a_idx"),
        ),
        migrations.AddIndex(
            model_name="kioskdevice",
            index=models.Index(
                fields=["last_seen_at"], name="kiosks_kios_last_se_f63a79_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="kioskdevice",
            index=models.Index(
                fields=["is_active"], name="kiosks_kios_is_acti_9d3624_idx"
            ),
        ),
    ]
