# Generated by Django 6.0.1 on 2026-09-07 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kiosks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="kioskdevice",
            name="deployed_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp when device was deployed", null=True
            ),
        ),
        migrations.AddField(
            model_name="kioskdevice",
            name="is_deployed",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Indicates whether the kiosk device is deployed at physical location",
            ),
        ),
        migrations.AddField(
            model_name="kioskdevice",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Optional device latitude coordinate",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="kioskdevice",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Optional device longitude coordinate",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="kioskprofile",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Optional profile latitude coordinate",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="kioskprofile",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Optional profile longitude coordinate",
                max_digits=9,
                null=True,
            ),
        ),
    ]
