# Generated by Django 6.1 on 2026-09-08 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kiosks", "0002_kioskdevice_deployed_at_kioskdevice_is_deployed_and_more"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="kioskdevice",
            name="assigned_products",
            field=models.ManyToManyField(
                blank=True,
                help_text="Products assigned to display on this kiosk",
                related_name="assigned_kiosks",
                to="products.product",
            ),
        ),
    ]
