# Generated by Django 6.1 on 2026-09-08 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kiosks", "0003_kioskdevice_assigned_products"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="kioskdevice",
            name="assigned_products",
        ),
    ]
