# Generated by Django 6.0.1 on 2026-09-22 11:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kiosks", "0005_kioskdevice_assigned_products"),
        ("products", "0002_add_category_image"),
        ("stores", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KioskUpdateLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "from_version_code",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("to_version_code", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UP_TO_DATE", "Up to Date"),
                            ("UPDATE_AVAILABLE", "Update Available"),
                            ("DOWNLOADING", "Downloading"),
                            ("INSTALLING", "Installing"),
                            ("UPDATED", "Updated"),
                            ("FAILED", "Failed"),
                            ("OFFLINE", "Offline"),
                        ],
                        max_length=30,
                    ),
                ),
                ("message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "Kiosk Update Log",
                "verbose_name_plural": "Kiosk Update Logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="kioskdevice",
            name="check_update_requested",
            field=models.BooleanField(
                default=False,
                help_text="Signals device to perform an immediate update check",
            ),
        ),
        migrations.AddField(
            model_name="kioskdevice",
            name="current_app_version_code",
            field=models.PositiveIntegerField(
                db_index=True, default=1, help_text="Current Android app versionCode"
            ),
        ),
        migrations.AddField(
            model_name="kioskdevice",
            name="force_update_requested",
            field=models.BooleanField(
                default=False,
                help_text="Signals device to immediately download and install latest release",
            ),
        ),
        migrations.AddField(
            model_name="kioskdevice",
            name="last_update_check",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp of last update check", null=True
            ),
        ),
        migrations.AddField(
            model_name="kioskdevice",
            name="update_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="kioskdevice",
            name="update_error",
            field=models.TextField(
                blank=True,
                help_text="Latest update failure or verification error",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="kioskdevice",
            name="update_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="kioskdevice",
            name="update_status",
            field=models.CharField(
                choices=[
                    ("UP_TO_DATE", "Up to Date"),
                    ("UPDATE_AVAILABLE", "Update Available"),
                    ("DOWNLOADING", "Downloading"),
                    ("INSTALLING", "Installing"),
                    ("UPDATED", "Updated"),
                    ("FAILED", "Failed"),
                    ("OFFLINE", "Offline"),
                ],
                db_index=True,
                default="UP_TO_DATE",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="AppRelease",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "version_name",
                    models.CharField(
                        help_text="Semantic version string, e.g. 1.0.5", max_length=50
                    ),
                ),
                (
                    "version_code",
                    models.PositiveIntegerField(
                        db_index=True,
                        help_text="Monotonically increasing integer Android versionCode",
                        unique=True,
                    ),
                ),
                (
                    "release_title",
                    models.CharField(
                        help_text="Release title, e.g. Product Display Improvements",
                        max_length=255,
                    ),
                ),
                (
                    "release_notes",
                    models.TextField(
                        help_text="Release notes / changelog items (one per line or markdown)"
                    ),
                ),
                (
                    "apk_file",
                    models.FileField(
                        blank=True,
                        help_text="APK installer binary file",
                        null=True,
                        upload_to="apks/",
                    ),
                ),
                (
                    "apk_url",
                    models.URLField(
                        blank=True,
                        help_text="Direct APK download URL (S3, CDN, or external VPS)",
                        max_length=500,
                    ),
                ),
                (
                    "apk_file_size",
                    models.PositiveBigIntegerField(
                        blank=True, help_text="File size in bytes", null=True
                    ),
                ),
                (
                    "checksum_sha256",
                    models.CharField(
                        blank=True, help_text="SHA-256 hash checksum", max_length=64
                    ),
                ),
                (
                    "is_mandatory",
                    models.BooleanField(
                        default=False,
                        help_text="Require kiosks to update before further operation",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Enable or disable this release",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Published releases are discoverable by kiosks",
                    ),
                ),
                (
                    "minimum_supported_version",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Minimum current versionCode required on kiosk before upgrading",
                        null=True,
                    ),
                ),
                (
                    "target_device_type",
                    models.CharField(
                        choices=[
                            ("ALL", "All Kiosks"),
                            ("ANDROID_TV", "Android TV"),
                            ("TABLET", "Tablet / Touch Screen"),
                            ("STANDALONE", "Standalone Kiosk"),
                        ],
                        default="ALL",
                        help_text="Target device hardware family",
                        max_length=50,
                    ),
                ),
                (
                    "staged_rollout_percentage",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="Percentage (1-100) of kiosk fleet to deploy to in stages",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="app_releases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_kiosks",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Optional selective targeting: if selected, only these specific kiosks receive the update",
                        related_name="targeted_releases",
                        to="kiosks.kioskdevice",
                    ),
                ),
            ],
            options={
                "verbose_name": "App Release",
                "verbose_name_plural": "App Releases",
                "ordering": ["-version_code"],
            },
        ),
        migrations.AddField(
            model_name="kioskdevice",
            name="pending_update_release",
            field=models.ForeignKey(
                blank=True,
                help_text="Target release currently queued or being installed",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pending_kiosks",
                to="kiosks.apprelease",
            ),
        ),
        migrations.AddIndex(
            model_name="kioskdevice",
            index=models.Index(
                fields=["update_status"], name="kiosks_kios_update__efa1af_idx"
            ),
        ),
        migrations.AddField(
            model_name="kioskupdatelog",
            name="kiosk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="update_logs",
                to="kiosks.kioskdevice",
            ),
        ),
        migrations.AddField(
            model_name="kioskupdatelog",
            name="release",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="device_logs",
                to="kiosks.apprelease",
            ),
        ),
    ]
