# Generated by Django 6.0.1 on 2026-09-07 05:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="Store name", max_length=255)),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Unique store identification code",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("address", models.TextField(blank=True, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("country", models.CharField(default="India", max_length=100)),
                (
                    "contact_person",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "contact_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Store",
                "verbose_name_plural": "Stores",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["code"], name="stores_stor_code_1c926b_idx"),
                    models.Index(
                        fields=["is_active"], name="stores_stor_is_acti_12939d_idx"
                    ),
                ],
            },
        ),
    ]
