# Generated by Django 5.2.17 on 2026-09-15 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Category representative image (white background preferred)",
                null=True,
                upload_to="categories/",
            ),
        ),
    ]
