# Generated by Django 6.0.1 on 2026-09-29 05:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_category_options_category_display_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="applicable_areas",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of applicable installation and industry areas",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="certifications",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of certifications with test sub-points",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="features",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of feature points with optional sub-points",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="in_house_tests",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of in-house tests with sub-points",
            ),
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Variant title/name (e.g. Copper Bonded Rod 100 Microns, With V Strip 100 Microns)",
                        max_length=255,
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        blank=True,
                        help_text="Variant unique SKU or item code",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("stock", models.IntegerField(default=100)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Variant specific image",
                        null=True,
                        upload_to="products/variants/",
                    ),
                ),
                (
                    "specifications",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Dynamic technical specifications for this variant",
                    ),
                ),
                (
                    "features",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Features with points and sub-points",
                    ),
                ),
                (
                    "certifications",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Certifications with points and sub-points",
                    ),
                ),
                (
                    "in_house_tests",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="In-house test points and sub-points",
                    ),
                ),
                (
                    "applicable_areas",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Applicable industry and installation areas",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Sort order among product variants"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Parent product this variant belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "created_at", "name"],
            },
        ),
    ]
