# Generated by Django 6.0.1 on 2026-09-29 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_product_applicable_areas_product_certifications_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent main product if this is a variant product",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="child_variants",
                to="products.product",
            ),
        ),
        migrations.DeleteModel(
            name="ProductVariant",
        ),
    ]
