# Generated by Django 6.0.1 on 2026-09-29 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_alter_product_parent_delete_productvariant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, unique=True
            ),
        ),
    ]
