# Generated by Django 6.0.1 on 2026-09-30 06:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_alter_product_sku"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductShare",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional customer name",
                        max_length=255,
                    ),
                ),
                (
                    "customer_phone",
                    models.CharField(help_text="Customer mobile number", max_length=50),
                ),
                ("shared_via", models.CharField(default="whatsapp", max_length=50)),
                (
                    "options",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of sections shared (e.g. overview, specs)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shares",
                        to="products.product",
                    ),
                ),
                (
                    "staff_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff user who shared this product detail",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="product_shares",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="variant_shares",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
